server:
  port: 48080

--- #################### 数据库相关配置 ####################
spring:
  main:
    allow-bean-definition-overriding: true
  shardingsphere:
    props:
      sql:
        show: true
    datasource:
      demo0:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://42.192.183.193:3306/demo0?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=CTT
        username: root
        password: lzj2515628
        type: com.alibaba.druid.pool.DruidDataSource
        maxActive: 20
        min-idle: 5
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
        filters: stat,wall,log4j2
      demo1:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://42.192.183.193:3306/demo1?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=CTT
        username: root
        password: lzj2515628
        type: com.alibaba.druid.pool.DruidDataSource
        maxActive: 20
        min-idle: 5
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
        filters: stat,wall,log4j2
      names: demo0,demo1
    sharding:
      binding-tables: pay_parent,pay_parent_item
      broadcast-tables: t_address
      default-database-strategy:
        ## 实际数据库分库路由键和路由算法
        standard:
          precise-algorithm-class-name: com.ilearning.common.datasource.shardingJdbc.DatabasePreciseShardingAlgorithm
          range-algorithm-class-name: com.ilearning.common.datasource.shardingJdbc.DatabasePreciseRangeShardingAlgorithm
          sharding-column: user_id
      tables:
        pay_parent:
          ## 实际数据库分库数量和分表数量
          actual-data-nodes: demo$->{0..1}.pay_parent_$->{0..1}
          ## 表主键策略
          key-generator:
            column: id
            props:
              worker:
                id: 123
            type: SNOWFLAKE
          table-strategy:
            ## 实际数据库分表路由键和路由算法
            standard:
              precise-algorithm-class-name: com.ilearning.common.datasource.shardingJdbc.MyPreciseTableShardingAlgorithm
              range-algorithm-class-name: com.ilearning.common.datasource.shardingJdbc.MyPreciseTableRangeShardingAlgorithm
              sharding-column: user_id
        pay_parent_item:
          actual-data-nodes: demo$->{0..1}.pay_parent_item_$->{0..1}
          key-generator:
            column: id
            props:
              worker:
                id: 123
            type: SNOWFLAKE
          table-strategy:
            standard:
              precise-algorithm-class-name: com.ilearning.common.datasource.shardingJdbc.MyPreciseTableShardingAlgorithm
              range-algorithm-class-name: com.ilearning.common.datasource.shardingJdbc.MyPreciseTableRangeShardingAlgorithm
              sharding-column: user_id

  # Redis 配置。Redisson 默认的配置足够使用，一般不需要进行调优
  redis:
    host: 42.192.183.193 # 地址
    port: 26379 # 端口
    database: 1 # 数据库索引
props:
  sql:
    show=true: