server:
  port: 48080

--- #################### 数据库相关配置 ####################
spring:
  main:
    allow-bean-definition-overriding: true
  shardingsphere:
    props:
      sql:
        show: true
    datasource:
      demo0:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://42.192.183.193:3306/demo0?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=CTT
        username: root
        password: lzj2515628
        type: com.alibaba.druid.pool.DruidDataSource
        maxActive: 20
        min-idle: 5
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
        filters: stat,wall,log4j2
      demo1:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://42.192.183.193:3306/demo1?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=CTT
        username: root
        password: lzj2515628
        type: com.alibaba.druid.pool.DruidDataSource
        maxActive: 20
        min-idle: 5
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
        filters: stat,wall,log4j2
      names: demo0,demo1
      baseName: demo
    sharding:
      binding-tables: pay_parent,pay_parent_item
      broadcast-tables: tenant_user
      tables:
        pay_parent:
          ## 实际数据库分库数量和分表数量
          actual-data-nodes: demo$->{0..1}.pay_parent_$->{0..1}
          ## 表主键策略
          key-generator:
            column: id
            props:
              worker:
                id: 123
            type: SNOWFLAKE
          table-strategy:
            ## 实际数据库分表路由键和路由算法
            hint:
              algorithm-class-name: com.ilearning.common.datasource.shardingJdbc.MyHintTableShardingAlgorithm
          database-strategy:
            ## 实际数据库分表路由键和路由算法
            hint:
              algorithm-class-name: com.ilearning.common.datasource.shardingJdbc.MyHintDatabaseShardingAlgorithm
        pay_parent_item:
          actual-data-nodes: demo$->{0..1}.pay_parent_item_$->{0..1}
          key-generator:
            column: id
            props:
              worker:
                id: 123
            type: SNOWFLAKE
          table-strategy:
            hint:
              algorithm-class-name: com.ilearning.common.datasource.shardingJdbc.MyHintTableShardingAlgorithm
          database-strategy:
            ## 实际数据库分表路由键和路由算法
            hint:
              algorithm-class-name: com.ilearning.common.datasource.shardingJdbc.MyHintDatabaseShardingAlgorithm
  # Redis 配置。Redisson 默认的配置足够使用，一般不需要进行调优
  redis:
    host: 42.192.183.193 # 地址
    port: 26379 # 端口
    database: 3 # 数据库索引
    password: luozijing@2021
    timeout: 5000ms
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
  rabbitmq:
    host: 42.192.183.193
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        #        acknowledge-mode: manual   # 配置该消费者的ack方式为手动
        acknowledge-mode: auto   # 配置该消费者的ack方式为自动
        default-requeue-rejected: false
        #设置消费失败后重发
        retry:
          #重发次数
          max-attempts: 3
          #开启重发
          enabled: true
          # 重试间隔(ms)
          initial-interval: 5000
props:
  sql:
    show=true:

canal:
  serverAddress: 42.192.183.193
  serverPort: 11111
  instance: #多个instance
    - example