
DROP SCHEMA IF EXISTS demo0;
DROP SCHEMA IF EXISTS demo1;



 --Should sync from master-salve automatically
 CREATE TABLE IF NOT EXISTS demo0.pay_parent_0 (id BIGINT NOT NULL AUTO_INCREMENT, user_id INT NOT NULL, status VARCHAR(50), PRIMARY KEY (id));
 CREATE TABLE IF NOT EXISTS demo0.pay_parent_1 (id BIGINT NOT NULL AUTO_INCREMENT, user_id INT NOT NULL, status VARCHAR(50), PRIMARY KEY (id));
 CREATE TABLE IF NOT EXISTS demo1.pay_parent_0 (id BIGINT NOT NULL AUTO_INCREMENT, user_id INT NOT NULL, status VARCHAR(50), PRIMARY KEY (id));
 CREATE TABLE IF NOT EXISTS demo1.pay_parent_1 (id BIGINT NOT NULL AUTO_INCREMENT, user_id INT NOT NULL, status VARCHAR(50), PRIMARY KEY (id));

 CREATE TABLE IF NOT EXISTS demo0.pay_parent_item_0 (id BIGINT NOT NULL AUTO_INCREMENT, order_id BIGINT NOT NULL, user_id INT NOT NULL, status VARCHAR(50), PRIMARY KEY (id));
 CREATE TABLE IF NOT EXISTS demo0.pay_parent_item_1 (id BIGINT NOT NULL AUTO_INCREMENT, order_id BIGINT NOT NULL, user_id INT NOT NULL, status VARCHAR(50), PRIMARY KEY (id));
 CREATE TABLE IF NOT EXISTS demo1.pay_parent_item_0 (id BIGINT NOT NULL AUTO_INCREMENT, order_id BIGINT NOT NULL, user_id INT NOT NULL, status VARCHAR(50), PRIMARY KEY (id));
 CREATE TABLE IF NOT EXISTS demo1.pay_parent_item_1 (id BIGINT NOT NULL AUTO_INCREMENT, order_id BIGINT NOT NULL, user_id INT NOT NULL, status VARCHAR(50), PRIMARY KEY (id));

 ALTER TABLE demo1.pay_parent_item_1  ADD COLUMN
   `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
 ADD COLUMN  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
 ADD COLUMN  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  ADD COLUMN `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
 ADD COLUMN  `deleted` bit(1) NOT NULL DEFAULT '0' COMMENT '是否删除';